### ISSUE TITLE
Several bugs in Code

### ISSUE THREAD

**Issue by lnsongxf** [IRIS-Solutions-Team/Tutorial-Simple-SPBC-Model#2]
I tried to run the codes in matlab, and encounter some errors, and then I found  several bugs in the codes,

First: simulate_complex_shocks.m

The Simulate Consumption Demand Shock with Delayed Policy Reaction part, "sc = Scenario(m, startDate:endDate);” should be "sc = plan(m,startDate:endDate);"

Second: forecasts_with_judgment.m

Exogenise Interest Rates part, "sc1 = Scenario(mest, startFcst:endFcst);" should be "sc1 = plan(mest, startFcst:endFcst);"

Condition on Anticipated Interest Rates part, "sc2 = Scenario(mest, startFcst:endFcst);" should be "sc2 = plan(mest, startFcst:endFcst);"

Exogenised Interest Rates and Condition on Inflation part, "sc4 = Scenario(mest, startFcst:endFcst);" should be "sc4= plan(mest, startFcst:endFcst);"

After the modification, the codes are OK.

I think these are minor bugs, and I really appreciate your great contribution of providing such a poweful research tool.

**Comment by jaromir-benes** [comment]
Tutorial upgraded.
